name: "rename"
version: "0.0.1"
usage: "rename a release"
description: |-
  rename a release.
ignoreFlags: false
useTunnel: true
command: "$HELM_PLUGIN_DIR/helm-rename"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
